services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ewallet_db
      POSTGRES_USER: ewallet_owner
      POSTGRES_PASSWORD: adminPasswrd
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ewallet_owner -d ewallet_db -h localhost -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
